/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcceptInvitationRouteImport } from './routes/accept-invitation'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as OrganizationSettingsRouteImport } from './routes/organization/settings'
import { Route as OrganizationMembersRouteImport } from './routes/organization/members'
import { Route as OnboardingInviteMembersRouteImport } from './routes/onboarding/invite-members'
import { Route as OnboardingCreateOrganizationRouteImport } from './routes/onboarding/create-organization'
import { Route as InvitationIdRouteImport } from './routes/invitation/$id'
import { Route as AuthAuthViewRouteImport } from './routes/auth/$authView'
import { Route as AccountVerifyEmailRouteImport } from './routes/account/verify-email'
import { Route as AccountSettingsRouteImport } from './routes/account/settings'
import { Route as AccountAccountViewRouteImport } from './routes/account/$accountView'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInvitationRoute = AcceptInvitationRouteImport.update({
  id: '/accept-invitation',
  path: '/accept-invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationSettingsRoute = OrganizationSettingsRouteImport.update({
  id: '/organization/settings',
  path: '/organization/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationMembersRoute = OrganizationMembersRouteImport.update({
  id: '/organization/members',
  path: '/organization/members',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingInviteMembersRoute = OnboardingInviteMembersRouteImport.update({
  id: '/onboarding/invite-members',
  path: '/onboarding/invite-members',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingCreateOrganizationRoute =
  OnboardingCreateOrganizationRouteImport.update({
    id: '/onboarding/create-organization',
    path: '/onboarding/create-organization',
    getParentRoute: () => rootRouteImport,
  } as any)
const InvitationIdRoute = InvitationIdRouteImport.update({
  id: '/invitation/$id',
  path: '/invitation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthAuthViewRoute = AuthAuthViewRouteImport.update({
  id: '/auth/$authView',
  path: '/auth/$authView',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountVerifyEmailRoute = AccountVerifyEmailRouteImport.update({
  id: '/account/verify-email',
  path: '/account/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/account/settings',
  path: '/account/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountAccountViewRoute = AccountAccountViewRouteImport.update({
  id: '/account/$accountView',
  path: '/account/$accountView',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/onboarding/create-organization': typeof OnboardingCreateOrganizationRoute
  '/onboarding/invite-members': typeof OnboardingInviteMembersRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/onboarding/create-organization': typeof OnboardingCreateOrganizationRoute
  '/onboarding/invite-members': typeof OnboardingInviteMembersRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/onboarding': typeof OnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accept-invitation': typeof AcceptInvitationRoute
  '/dashboard': typeof DashboardRoute
  '/account/$accountView': typeof AccountAccountViewRoute
  '/account/settings': typeof AccountSettingsRoute
  '/account/verify-email': typeof AccountVerifyEmailRoute
  '/auth/$authView': typeof AuthAuthViewRoute
  '/invitation/$id': typeof InvitationIdRoute
  '/onboarding/create-organization': typeof OnboardingCreateOrganizationRoute
  '/onboarding/invite-members': typeof OnboardingInviteMembersRoute
  '/organization/members': typeof OrganizationMembersRoute
  '/organization/settings': typeof OrganizationSettingsRoute
  '/onboarding/': typeof OnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/account/$accountView'
    | '/account/settings'
    | '/account/verify-email'
    | '/auth/$authView'
    | '/invitation/$id'
    | '/onboarding/create-organization'
    | '/onboarding/invite-members'
    | '/organization/members'
    | '/organization/settings'
    | '/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/account/$accountView'
    | '/account/settings'
    | '/account/verify-email'
    | '/auth/$authView'
    | '/invitation/$id'
    | '/onboarding/create-organization'
    | '/onboarding/invite-members'
    | '/organization/members'
    | '/organization/settings'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/accept-invitation'
    | '/dashboard'
    | '/account/$accountView'
    | '/account/settings'
    | '/account/verify-email'
    | '/auth/$authView'
    | '/invitation/$id'
    | '/onboarding/create-organization'
    | '/onboarding/invite-members'
    | '/organization/members'
    | '/organization/settings'
    | '/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcceptInvitationRoute: typeof AcceptInvitationRoute
  DashboardRoute: typeof DashboardRoute
  AccountAccountViewRoute: typeof AccountAccountViewRoute
  AccountSettingsRoute: typeof AccountSettingsRoute
  AccountVerifyEmailRoute: typeof AccountVerifyEmailRoute
  AuthAuthViewRoute: typeof AuthAuthViewRoute
  InvitationIdRoute: typeof InvitationIdRoute
  OnboardingCreateOrganizationRoute: typeof OnboardingCreateOrganizationRoute
  OnboardingInviteMembersRoute: typeof OnboardingInviteMembersRoute
  OrganizationMembersRoute: typeof OrganizationMembersRoute
  OrganizationSettingsRoute: typeof OrganizationSettingsRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invitation': {
      id: '/accept-invitation'
      path: '/accept-invitation'
      fullPath: '/accept-invitation'
      preLoaderRoute: typeof AcceptInvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/settings': {
      id: '/organization/settings'
      path: '/organization/settings'
      fullPath: '/organization/settings'
      preLoaderRoute: typeof OrganizationSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organization/members': {
      id: '/organization/members'
      path: '/organization/members'
      fullPath: '/organization/members'
      preLoaderRoute: typeof OrganizationMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/invite-members': {
      id: '/onboarding/invite-members'
      path: '/onboarding/invite-members'
      fullPath: '/onboarding/invite-members'
      preLoaderRoute: typeof OnboardingInviteMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/create-organization': {
      id: '/onboarding/create-organization'
      path: '/onboarding/create-organization'
      fullPath: '/onboarding/create-organization'
      preLoaderRoute: typeof OnboardingCreateOrganizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation/$id': {
      id: '/invitation/$id'
      path: '/invitation/$id'
      fullPath: '/invitation/$id'
      preLoaderRoute: typeof InvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$authView': {
      id: '/auth/$authView'
      path: '/auth/$authView'
      fullPath: '/auth/$authView'
      preLoaderRoute: typeof AuthAuthViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/verify-email': {
      id: '/account/verify-email'
      path: '/account/verify-email'
      fullPath: '/account/verify-email'
      preLoaderRoute: typeof AccountVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/account/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/$accountView': {
      id: '/account/$accountView'
      path: '/account/$accountView'
      fullPath: '/account/$accountView'
      preLoaderRoute: typeof AccountAccountViewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcceptInvitationRoute: AcceptInvitationRoute,
  DashboardRoute: DashboardRoute,
  AccountAccountViewRoute: AccountAccountViewRoute,
  AccountSettingsRoute: AccountSettingsRoute,
  AccountVerifyEmailRoute: AccountVerifyEmailRoute,
  AuthAuthViewRoute: AuthAuthViewRoute,
  InvitationIdRoute: InvitationIdRoute,
  OnboardingCreateOrganizationRoute: OnboardingCreateOrganizationRoute,
  OnboardingInviteMembersRoute: OnboardingInviteMembersRoute,
  OrganizationMembersRoute: OrganizationMembersRoute,
  OrganizationSettingsRoute: OrganizationSettingsRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
